nativeapp
snowflakedb/snowflake-cli pull request #1140
Opened 2024-05-29 11:04 UTC by sfc-gh-pczajka

### Pre-review checklist
   * [ ] I've confirmed that instructions included in README.md are still correct after my changes in the codebase.
   * [ ] I've added or updated automated unit tests to verify correctness of my new code.
   * [ ] I've added or updated integration tests to verify correctness of my new code.
   * [ ] I've confirmed that my changes are working by executing CLI's commands manually.
   * [ ] I've confirmed that my changes are up-to-date with the target branch.
   * [ ] I've described my changes in the release notes.
   * [ ] I've described my changes in the section below.

### Changes description
Refactor changing Typer instances from static ones to dynamically created during command registration.

What changed:
* `commands` modules got wrapped into `create_app()` function, which is executed during plugin registration

2024-05-29 11:45 UTC, sfc-gh-astus approved these changes

2024-05-29 11:49 UTC, sfc-gh-pjob approved these changes

2024-05-29 11:56 UTC, sfc-gh-turbaszek requested changes
Have we considered doing this in other way? For example creating a "typer" instance that can be "generated" when neccessary?

2024-06-07 11:19 UTC, sfc-gh-pczajka commented
Implemented by https://github.com/snowflakedb/snowflake-cli/pull/1166

2024-06-07 11:19 UTC, closed without merging